const { contentTypes } = require("strapi-utils");
const { constants } = contentTypes;
const {
  ID_ATTRIBUTE,
  PUBLISHED_AT_ATTRIBUTE,
  CREATED_BY_ATTRIBUTE,
  UPDATED_BY_ATTRIBUTE,
  SINGLE_TYPE,
  COLLECTION_TYPE,
} = constants;

const ATTRIBUTES = {
  ID: ID_ATTRIBUTE,
  PUBLISHED_AT: PUBLISHED_AT_ATTRIBUTE,
  CREATED_BY: CREATED_BY_ATTRIBUTE,
  UPDATED_BY: UPDATED_BY_ATTRIBUTE,
};

const TYPES = {
  SINGLE: SINGLE_TYPE,
  COLLECTION: COLLECTION_TYPE,
};

module.exports = { ATTRIBUTES, TYPES };
